# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 94ef19ab875eb388688417b393fea69c9cb32f001425ed8aa4b269594a705c0659c1fbdcb582279b5d922a598a2442c3451a07343a0ad1bb69ad42ce36b13c93

test:
  secret_key_base: 961d37ae8718cf8ac896d1fd7900a603e92745630156c3576946e3bc2089996bc5f68ff7b1bd99bb999ebc5c0737a212e8487d0a93ef9fec89dc2242d43a9bc9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
